apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vtt-maps-site.fullname" . }}-secrets
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secretEnv.MONGO_URI | quote }}
  DISCORD_CLIENT_ID: {{ .Values.secretEnv.DISCORD_CLIENT_ID | quote }}
  DISCORD_CLIENT_SECRET: {{ .Values.secretEnv.DISCORD_CLIENT_SECRET | quote }}
  DISCORD_REDIRECT_URI: {{ .Values.secretEnv.DISCORD_REDIRECT_URI | quote }}
  JWT_SECRET: {{ .Values.secretEnv.JWT_SECRET | quote }}
  SUPER_ADMIN_DISCORD_ID: {{ .Values.secretEnv.SUPER_ADMIN_DISCORD_ID | quote }}
  GITHUB_URL: {{ .Values.secretEnv.GITHUB_URL | quote }}
  GITHUB_TOKEN: {{ .Values.secretEnv.GITHUB_TOKEN | quote }}
  RUSTFS_ENDPOINT: {{ .Values.secretEnv.RUSTFS_ENDPOINT | quote }}
  RUSTFS_BUCKET: {{ .Values.secretEnv.RUSTFS_BUCKET | quote }}
  RUSTFS_ACCESS_KEY: {{ .Values.secretEnv.RUSTFS_ACCESS_KEY | quote }}
  RUSTFS_SECRET_KEY: {{ .Values.secretEnv.RUSTFS_SECRET_KEY | quote }}
  RUSTFS_PUBLIC_URL_BASE: {{ .Values.secretEnv.RUSTFS_PUBLIC_URL_BASE | quote }}
